import type { IRelationshipGraphDemoDataService } from "./IRelationshipGraphDemoDataService";
import type { IRelationshipGraphService } from "./IRelationshipGraphService";

export class RelationshipGraphDemoDataService implements IRelationshipGraphDemoDataService {
  async createDemoData(service: IRelationshipGraphService): Promise<void> {
    const defaultPermissions = { defaultLevel: 0, users: [] };

    const createNodeAttributes = () => {
      return {
        color: "#000",
        shape: "ellipse",
        size: 30,
        "border-color": "#000",
        "border-width": 0,
        "background-color": "#999",
        "background-opacity": 1,
        opacity: 1,
        visibility: "visible",
        events: "yes",
        "text-events": "no",
        label: "",
        "font-size": 16,
        "font-family": "Helvetica Neue, Helvetica, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
        "text-valign": "top",
        "text-halign": "center",
        "text-justification": "auto",
        "text-wrap": "none",
        "text-overflow-wrap": "whitespace",
        "text-max-width": 9999,
        "text-rotation": "none",
        "text-margin-x": 0,
        "text-margin-y": 0,
        "line-height": 1,
        display: "element",
        "text-outline-color": "#000",
        "text-outline-width": 0,
        "text-outline-opacity": 1,
        "text-opacity": 1,
        "text-decoration": "none",
        "text-transform": "none",
        "text-background-color": "#000",
        "text-background-opacity": 0,
        "text-background-shape": "rectangle",
        "text-background-padding": 0,
        "text-border-color": "#000",
        "text-border-width": 0,
        "text-border-style": "solid",
        "text-border-opacity": 0,
        "min-zoomed-font-size": 0,
        "overlay-color": "#000",
        "overlay-opacity": 0,
        "overlay-padding": 10,
        "overlay-shape": "roundrectangle",
        "overlay-corner-radius": "auto",
        "underlay-color": "#000",
        "underlay-opacity": 0,
        "underlay-padding": 10,
        "underlay-shape": "roundrectangle",
        "underlay-corner-radius": "auto",
        "transition-property": "none",
        "transition-duration": 0,
        "transition-delay": 0,
        "transition-timing-function": "linear",
        "z-index": 0,
        "z-compound-depth": "auto",
        "z-index-compare": "auto",
        "box-select-labels": "no",
        width: 30,
        height: 30,
        "background-image": "none",
        "background-image-crossorigin": "anonymous",
        "background-image-opacity": 1,
        "background-image-containment": "inside",
        "background-image-smoothing": "yes",
        "background-position-x": "50%",
        "background-position-y": "50%",
        "background-offset-x": 0,
        "background-offset-y": 0,
        "background-width-relative-to": "include-padding",
        "background-height-relative-to": "include-padding",
        "background-repeat": "no-repeat",
        "background-fit": "none",
        "background-clip": "node",
        "background-width": "auto",
        "background-height": "auto",
        "corner-radius": "auto",
        padding: 0,
        "border-style": "solid",
        "border-opacity": 1,
        "border-dash-pattern": [4, 2],
        "border-dash-offset": 0,
        "border-cap": "butt",
        "border-join": "miter",
        "border-position": "center",
        "outline-color": "#999",
        "outline-width": 0,
        "outline-opacity": 1,
        "outline-offset": 0,
        "outline-style": "solid",
        "background-gradient-direction": "to-bottom",
        "background-gradient-stop-colors": "#999",
        "background-gradient-stop-positions": "0%",
        "background-blacken": 0,
        "background-fill": "solid",
        "shape-polygon-points": "-1, -1,   1, -1,   1, 1,   -1, 1",
        "bounds-expansion": 0,
        "pie-size": "100%",
        "pie-hole": 0,
        "pie-start-angle": "0deg",
        "padding-relative-to": "width",
        position: "origin",
        "compound-sizing-wrt-labels": "include",
        "min-width": 0,
        "min-height": 0,
        ghost: "no",
        "ghost-offset-x": 0,
        "ghost-offset-y": 0,
        "ghost-opacity": 0,
      } as any;
    };

    const createEdgeAttributes = () => {
      return {
        color: "#000",
        opacity: 1,
        visibility: "visible",
        events: "yes",
        "text-events": "no",
        label: "",
        "font-size": 16,
        "font-family": "Helvetica Neue, Helvetica, sans-serif",
        "font-weight": "normal",
        "font-style": "normal",
        "text-valign": "top",
        "text-halign": "center",
        "text-justification": "auto",
        "text-wrap": "none",
        "text-overflow-wrap": "whitespace",
        "text-max-width": 9999,
        "text-rotation": "none",
        "text-margin-x": 0,
        "text-margin-y": 0,
        "line-height": 1,
        display: "element",
        "text-outline-color": "#000",
        "text-outline-width": 0,
        "text-outline-opacity": 1,
        "text-opacity": 1,
        "text-decoration": "none",
        "text-transform": "none",
        "text-background-color": "#000",
        "text-background-opacity": 0,
        "text-background-shape": "rectangle",
        "text-background-padding": 0,
        "text-border-color": "#000",
        "text-border-width": 0,
        "text-border-style": "solid",
        "text-border-opacity": 0,
        "min-zoomed-font-size": 0,
        "overlay-color": "#000",
        "overlay-opacity": 0,
        "overlay-padding": 10,
        "overlay-shape": "roundrectangle",
        "overlay-corner-radius": "auto",
        "underlay-color": "#000",
        "underlay-opacity": 0,
        "underlay-padding": 10,
        "underlay-shape": "roundrectangle",
        "underlay-corner-radius": "auto",
        "transition-property": "none",
        "transition-duration": 0,
        "transition-delay": 0,
        "transition-timing-function": "linear",
        "z-index": 0,
        "z-compound-depth": "auto",
        "z-index-compare": "auto",
        "box-select-labels": "no",
        width: 3,
        "line-color": "#999",
        "line-opacity": 1,
        "line-style": "solid",
        "curve-style": "haystack",
        "target-arrow-shape": "none",
        "target-arrow-color": "#999",
        "target-arrow-width": 1,
        "target-arrow-fill": "filled",
        "source-arrow-shape": "none",
        "source-arrow-color": "#999",
        "source-arrow-width": 1,
        "source-arrow-fill": "filled",
        "mid-source-arrow-shape": "none",
        "mid-source-arrow-color": "#999",
        "mid-source-arrow-width": 1,
        "mid-source-arrow-fill": "filled",
        "mid-target-arrow-shape": "none",
        "mid-target-arrow-color": "#999",
        "mid-target-arrow-width": 1,
        "mid-target-arrow-fill": "filled",
        "line-cap": "butt",
        "line-fill": "solid",
        "line-outline-width": 0,
        "line-outline-color": "#000",
        "line-gradient-stop-colors": "#999",
        "line-gradient-stop-positions": "0%",
        "line-dash-pattern": [6, 3],
        "line-dash-offset": 0,
        "control-point-step-size": 40,
        "control-point-weights": 0.5,
        "segment-weights": 0.5,
        "segment-distances": 20,
        "segment-radii": 15,
        "radius-type": "arc-radius",
        "taxi-turn": "50%",
        "taxi-radius": 15,
        "taxi-turn-min-distance": 10,
        "taxi-direction": "auto",
        "edge-distances": "intersection",
        "haystack-radius": 0,
        "arrow-scale": 1,
        "loop-direction": "-45deg",
        "loop-sweep": "-90deg",
        "source-distance-from-node": 0,
        "target-distance-from-node": 0,
        "source-endpoint": "outside-to-node",
        "target-endpoint": "outside-to-node",
        "source-label": "",
        "source-text-offset": 0,
        "source-text-margin-x": 0,
        "source-text-margin-y": 0,
        "source-text-rotation": "none",
        "target-label": "",
        "target-text-offset": 0,
        "target-text-margin-x": 0,
        "target-text-margin-y": 0,
        "target-text-rotation": "none",
      } as any;
    };

    await service.addNode({
      id: foundry.utils.randomID(),
      x: 150,
      y: 200,
      label: { value: "Bauer", permissions: defaultPermissions },
      type: { value: "person", permissions: defaultPermissions },
      globalPermissions: defaultPermissions,
      cytoScapeAttributes: {
        ...createNodeAttributes(),
        color: "#000000",
        "background-color": "#006400",
        shape: "ellipse",
        width: 80,
        height: 80,
        "border-color": "#000",
        "border-width": 0,
        "text-valign": "center",
        "text-halign": "center",
        "font-size": 14,
        "font-weight": "bold",
        "font-family": "Arial, sans-serif",
      },
    });

    await service.addNode({
      id: foundry.utils.randomID(),
      x: 450,
      y: 200,
      label: { value: "Müller", permissions: defaultPermissions },
      type: { value: "person", permissions: defaultPermissions },
      globalPermissions: defaultPermissions,
      cytoScapeAttributes: {
        ...createNodeAttributes(),
        color: "#000000",
        "background-color": "#F5DEB3",
        shape: "ellipse",
        width: 80,
        height: 80,
        "border-color": "#000",
        "border-width": 0,
        "text-valign": "center",
        "text-halign": "center",
        "font-size": 14,
        "font-weight": "bold",
        "font-family": "Arial, sans-serif",
        "background-opacity": 1,
        "outline-color": "#F5DEB3",
        "background-gradient-stop-colors": "#F5DEB3",
      },
    });

    await service.addEdge({
      id: foundry.utils.randomID(),
      source: service.getNodeByLabel("Bauer")?.id ?? "",
      target: service.getNodeByLabel("Müller")?.id ?? "",
      label: { value: "Weizen", permissions: defaultPermissions },
      type: "trade",
      globalPermissions: defaultPermissions,
      cytoScapeAttributes: {
        ...createEdgeAttributes(),
        color: "#000",
        "line-color": "#000",
        "line-opacity": 1,
        "line-style": "solid",
        "target-arrow-shape": "triangle",
        "target-arrow-color": "#000",
        "target-arrow-width": 2,
        "curve-style": "bezier",
        "text-margin-y": -10,
      },
    });
  }
}
